name: Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run:
          ./build.sh

      - name: Tag and push Docker image
        run:
          docker tag ap-yaml-checker ghcr.io/eijebong/archipelago-yaml-checker:main && docker push ghcr.io/eijebong/archipelago-yaml-checker:main

  deploy:
    environment: production
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: contains('refs/heads/main', github.ref)
    steps:
      - name: Setup SSH
        run: |
          mkdir .ssh
          chmod 700 .ssh
          echo "${{ secrets.DEPLOY_KEY }}" > .ssh/id_ed25519
          wc .ssh/id_ed25519
          wc -l .ssh/id_ed25519
          sha1sum .ssh/id_ed25519
          chmod 600 .ssh/id_ed25519
      - name: Trigger deployment
        run: ssh -o StrictHostKeyChecking=no -i .ssh/id_ed25519 ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOSTNAME }} touch .deploy-yaml-checker
